a = float(input ("Zadajte výšku v metroch, oddeluj bodkou: "))
b = float(input("Zadajte hmotnosť v kilogramoch, oddeluj bodkou: "))
d = b/(a**2)
print("Váš index BMI je:", d)
print("update_dev_branch")